apiVersion: core.napptive.com/v1alpha1
kind: ApplicationMetadata
name: "FastAPI"
version: v1.0.0
description: Web API using FastAPI framework
keywords:
  - "server"
  - "fastapi"
  - "python"
  - "github"
license: "MIT"
url: "https://github.com/oleksis/napptive-playground-py"
doc: "https://github.com/oleksis/napptive-playground-py#readme"
logo:
  - src: "https://fastapi.tiangolo.com/img/favicon.png"
    type: "image/png"
    size: "36x36"
